services:
  - type: web
    name: realtime-leaderboard-system
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: DB_CONNECTION_POOL_SIZE
        value: 10
      - key: RATE_LIMIT_WINDOW_MS
        value: 60000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: JWT_SECRET
        generateValue: true
      - key: LOG_LEVEL
        value: info 